// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: protov3/orchestrator.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	OrchestratorService_AssignTaskToWorker_FullMethodName = "/protov3.OrchestratorService/AssignTaskToWorker"
	OrchestratorService_SaveResult_FullMethodName         = "/protov3.OrchestratorService/SaveResult"
)

// OrchestratorServiceClient is the client API for OrchestratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrchestratorServiceClient interface {
	AssignTaskToWorker(ctx context.Context, in *AssignTaskToWorkerRequest, opts ...grpc.CallOption) (*AssignTaskToWorkerResponse, error)
	SaveResult(ctx context.Context, in *SaveResultRequest, opts ...grpc.CallOption) (*SaveResultResponse, error)
}

type orchestratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorServiceClient(cc grpc.ClientConnInterface) OrchestratorServiceClient {
	return &orchestratorServiceClient{cc}
}

func (c *orchestratorServiceClient) AssignTaskToWorker(ctx context.Context, in *AssignTaskToWorkerRequest, opts ...grpc.CallOption) (*AssignTaskToWorkerResponse, error) {
	out := new(AssignTaskToWorkerResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_AssignTaskToWorker_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) SaveResult(ctx context.Context, in *SaveResultRequest, opts ...grpc.CallOption) (*SaveResultResponse, error) {
	out := new(SaveResultResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_SaveResult_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorServiceServer is the server API for OrchestratorService service.
// All implementations must embed UnimplementedOrchestratorServiceServer
// for forward compatibility
type OrchestratorServiceServer interface {
	AssignTaskToWorker(context.Context, *AssignTaskToWorkerRequest) (*AssignTaskToWorkerResponse, error)
	SaveResult(context.Context, *SaveResultRequest) (*SaveResultResponse, error)
	mustEmbedUnimplementedOrchestratorServiceServer()
}

// UnimplementedOrchestratorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOrchestratorServiceServer struct {
}

func (UnimplementedOrchestratorServiceServer) AssignTaskToWorker(context.Context, *AssignTaskToWorkerRequest) (*AssignTaskToWorkerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignTaskToWorker not implemented")
}
func (UnimplementedOrchestratorServiceServer) SaveResult(context.Context, *SaveResultRequest) (*SaveResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveResult not implemented")
}
func (UnimplementedOrchestratorServiceServer) mustEmbedUnimplementedOrchestratorServiceServer() {}

// UnsafeOrchestratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorServiceServer will
// result in compilation errors.
type UnsafeOrchestratorServiceServer interface {
	mustEmbedUnimplementedOrchestratorServiceServer()
}

func RegisterOrchestratorServiceServer(s grpc.ServiceRegistrar, srv OrchestratorServiceServer) {
	s.RegisterService(&OrchestratorService_ServiceDesc, srv)
}

func _OrchestratorService_AssignTaskToWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignTaskToWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).AssignTaskToWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_AssignTaskToWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).AssignTaskToWorker(ctx, req.(*AssignTaskToWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_SaveResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).SaveResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_SaveResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).SaveResult(ctx, req.(*SaveResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrchestratorService_ServiceDesc is the grpc.ServiceDesc for OrchestratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protov3.OrchestratorService",
	HandlerType: (*OrchestratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignTaskToWorker",
			Handler:    _OrchestratorService_AssignTaskToWorker_Handler,
		},
		{
			MethodName: "SaveResult",
			Handler:    _OrchestratorService_SaveResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protov3/orchestrator.proto",
}

const (
	BackgroundWorkerService_ChangeTaskStatus_FullMethodName = "/protov3.BackgroundWorkerService/ChangeTaskStatus"
	BackgroundWorkerService_UpdateTaskStatus_FullMethodName = "/protov3.BackgroundWorkerService/UpdateTaskStatus"
	BackgroundWorkerService_HealthCheck_FullMethodName      = "/protov3.BackgroundWorkerService/HealthCheck"
)

// BackgroundWorkerServiceClient is the client API for BackgroundWorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackgroundWorkerServiceClient interface {
	ChangeTaskStatus(ctx context.Context, in *ChangeTaskStatusRequest, opts ...grpc.CallOption) (*ChangeTaskStatusResponse, error)
	UpdateTaskStatus(ctx context.Context, in *UpdateTaskStatusRequest, opts ...grpc.CallOption) (*UpdateTaskStatusResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type backgroundWorkerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBackgroundWorkerServiceClient(cc grpc.ClientConnInterface) BackgroundWorkerServiceClient {
	return &backgroundWorkerServiceClient{cc}
}

func (c *backgroundWorkerServiceClient) ChangeTaskStatus(ctx context.Context, in *ChangeTaskStatusRequest, opts ...grpc.CallOption) (*ChangeTaskStatusResponse, error) {
	out := new(ChangeTaskStatusResponse)
	err := c.cc.Invoke(ctx, BackgroundWorkerService_ChangeTaskStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backgroundWorkerServiceClient) UpdateTaskStatus(ctx context.Context, in *UpdateTaskStatusRequest, opts ...grpc.CallOption) (*UpdateTaskStatusResponse, error) {
	out := new(UpdateTaskStatusResponse)
	err := c.cc.Invoke(ctx, BackgroundWorkerService_UpdateTaskStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backgroundWorkerServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, BackgroundWorkerService_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackgroundWorkerServiceServer is the server API for BackgroundWorkerService service.
// All implementations must embed UnimplementedBackgroundWorkerServiceServer
// for forward compatibility
type BackgroundWorkerServiceServer interface {
	ChangeTaskStatus(context.Context, *ChangeTaskStatusRequest) (*ChangeTaskStatusResponse, error)
	UpdateTaskStatus(context.Context, *UpdateTaskStatusRequest) (*UpdateTaskStatusResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedBackgroundWorkerServiceServer()
}

// UnimplementedBackgroundWorkerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBackgroundWorkerServiceServer struct {
}

func (UnimplementedBackgroundWorkerServiceServer) ChangeTaskStatus(context.Context, *ChangeTaskStatusRequest) (*ChangeTaskStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeTaskStatus not implemented")
}
func (UnimplementedBackgroundWorkerServiceServer) UpdateTaskStatus(context.Context, *UpdateTaskStatusRequest) (*UpdateTaskStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTaskStatus not implemented")
}
func (UnimplementedBackgroundWorkerServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedBackgroundWorkerServiceServer) mustEmbedUnimplementedBackgroundWorkerServiceServer() {
}

// UnsafeBackgroundWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackgroundWorkerServiceServer will
// result in compilation errors.
type UnsafeBackgroundWorkerServiceServer interface {
	mustEmbedUnimplementedBackgroundWorkerServiceServer()
}

func RegisterBackgroundWorkerServiceServer(s grpc.ServiceRegistrar, srv BackgroundWorkerServiceServer) {
	s.RegisterService(&BackgroundWorkerService_ServiceDesc, srv)
}

func _BackgroundWorkerService_ChangeTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeTaskStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackgroundWorkerServiceServer).ChangeTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackgroundWorkerService_ChangeTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackgroundWorkerServiceServer).ChangeTaskStatus(ctx, req.(*ChangeTaskStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackgroundWorkerService_UpdateTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackgroundWorkerServiceServer).UpdateTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackgroundWorkerService_UpdateTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackgroundWorkerServiceServer).UpdateTaskStatus(ctx, req.(*UpdateTaskStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackgroundWorkerService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackgroundWorkerServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackgroundWorkerService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackgroundWorkerServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BackgroundWorkerService_ServiceDesc is the grpc.ServiceDesc for BackgroundWorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackgroundWorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protov3.BackgroundWorkerService",
	HandlerType: (*BackgroundWorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChangeTaskStatus",
			Handler:    _BackgroundWorkerService_ChangeTaskStatus_Handler,
		},
		{
			MethodName: "UpdateTaskStatus",
			Handler:    _BackgroundWorkerService_UpdateTaskStatus_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _BackgroundWorkerService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protov3/orchestrator.proto",
}
