// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protov3/orchestrator.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JobType int32

const (
	JobType_JOB_TYPE_SEND_MAIL_UNSPECIFIED   JobType = 0
	JobType_JOB_TYPE_RUN_COMMAND_UNSPECIFIED JobType = 1
)

var JobType_name = map[int32]string{
	0: "JOB_TYPE_SEND_MAIL_UNSPECIFIED",
	1: "JOB_TYPE_RUN_COMMAND_UNSPECIFIED",
}

var JobType_value = map[string]int32{
	"JOB_TYPE_SEND_MAIL_UNSPECIFIED":   0,
	"JOB_TYPE_RUN_COMMAND_UNSPECIFIED": 1,
}

func (x JobType) String() string {
	return proto.EnumName(JobType_name, int32(x))
}

func (JobType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ac1b54aa7dff77fd, []int{0}
}

type JobStatus int32

const (
	JobStatus_JOB_STATUS_COMPLETED_UNSPECIFIED JobStatus = 0
	JobStatus_JOB_STATUS_FAILED                JobStatus = 1
	JobStatus_JOB_STATUS_REGISTERED            JobStatus = 2
	JobStatus_JOB_STATUS_STARTED               JobStatus = 3
)

var JobStatus_name = map[int32]string{
	0: "JOB_STATUS_COMPLETED_UNSPECIFIED",
	1: "JOB_STATUS_FAILED",
	2: "JOB_STATUS_REGISTERED",
	3: "JOB_STATUS_STARTED",
}

var JobStatus_value = map[string]int32{
	"JOB_STATUS_COMPLETED_UNSPECIFIED": 0,
	"JOB_STATUS_FAILED":                1,
	"JOB_STATUS_REGISTERED":            2,
	"JOB_STATUS_STARTED":               3,
}

func (x JobStatus) String() string {
	return proto.EnumName(JobStatus_name, int32(x))
}

func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ac1b54aa7dff77fd, []int{1}
}

type AssignTaskToWorkerRequest struct {
	JobId                string    `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobType              JobType   `protobuf:"varint,2,opt,name=job_type,json=jobType,proto3,enum=protov3.JobType" json:"job_type,omitempty"`
	JobStatus            JobStatus `protobuf:"varint,3,opt,name=job_status,json=jobStatus,proto3,enum=protov3.JobStatus" json:"job_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AssignTaskToWorkerRequest) Reset()         { *m = AssignTaskToWorkerRequest{} }
func (m *AssignTaskToWorkerRequest) String() string { return proto.CompactTextString(m) }
func (*AssignTaskToWorkerRequest) ProtoMessage()    {}
func (*AssignTaskToWorkerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac1b54aa7dff77fd, []int{0}
}

func (m *AssignTaskToWorkerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssignTaskToWorkerRequest.Unmarshal(m, b)
}
func (m *AssignTaskToWorkerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssignTaskToWorkerRequest.Marshal(b, m, deterministic)
}
func (m *AssignTaskToWorkerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssignTaskToWorkerRequest.Merge(m, src)
}
func (m *AssignTaskToWorkerRequest) XXX_Size() int {
	return xxx_messageInfo_AssignTaskToWorkerRequest.Size(m)
}
func (m *AssignTaskToWorkerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AssignTaskToWorkerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AssignTaskToWorkerRequest proto.InternalMessageInfo

func (m *AssignTaskToWorkerRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *AssignTaskToWorkerRequest) GetJobType() JobType {
	if m != nil {
		return m.JobType
	}
	return JobType_JOB_TYPE_SEND_MAIL_UNSPECIFIED
}

func (m *AssignTaskToWorkerRequest) GetJobStatus() JobStatus {
	if m != nil {
		return m.JobStatus
	}
	return JobStatus_JOB_STATUS_COMPLETED_UNSPECIFIED
}

type AssignTaskToWorkerResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssignTaskToWorkerResponse) Reset()         { *m = AssignTaskToWorkerResponse{} }
func (m *AssignTaskToWorkerResponse) String() string { return proto.CompactTextString(m) }
func (*AssignTaskToWorkerResponse) ProtoMessage()    {}
func (*AssignTaskToWorkerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac1b54aa7dff77fd, []int{1}
}

func (m *AssignTaskToWorkerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssignTaskToWorkerResponse.Unmarshal(m, b)
}
func (m *AssignTaskToWorkerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssignTaskToWorkerResponse.Marshal(b, m, deterministic)
}
func (m *AssignTaskToWorkerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssignTaskToWorkerResponse.Merge(m, src)
}
func (m *AssignTaskToWorkerResponse) XXX_Size() int {
	return xxx_messageInfo_AssignTaskToWorkerResponse.Size(m)
}
func (m *AssignTaskToWorkerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AssignTaskToWorkerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AssignTaskToWorkerResponse proto.InternalMessageInfo

func (m *AssignTaskToWorkerResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type SaveResultRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveResultRequest) Reset()         { *m = SaveResultRequest{} }
func (m *SaveResultRequest) String() string { return proto.CompactTextString(m) }
func (*SaveResultRequest) ProtoMessage()    {}
func (*SaveResultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac1b54aa7dff77fd, []int{2}
}

func (m *SaveResultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveResultRequest.Unmarshal(m, b)
}
func (m *SaveResultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveResultRequest.Marshal(b, m, deterministic)
}
func (m *SaveResultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveResultRequest.Merge(m, src)
}
func (m *SaveResultRequest) XXX_Size() int {
	return xxx_messageInfo_SaveResultRequest.Size(m)
}
func (m *SaveResultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveResultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveResultRequest proto.InternalMessageInfo

func (m *SaveResultRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SaveResultRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type SaveResultResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveResultResponse) Reset()         { *m = SaveResultResponse{} }
func (m *SaveResultResponse) String() string { return proto.CompactTextString(m) }
func (*SaveResultResponse) ProtoMessage()    {}
func (*SaveResultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac1b54aa7dff77fd, []int{3}
}

func (m *SaveResultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveResultResponse.Unmarshal(m, b)
}
func (m *SaveResultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveResultResponse.Marshal(b, m, deterministic)
}
func (m *SaveResultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveResultResponse.Merge(m, src)
}
func (m *SaveResultResponse) XXX_Size() int {
	return xxx_messageInfo_SaveResultResponse.Size(m)
}
func (m *SaveResultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveResultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveResultResponse proto.InternalMessageInfo

func (m *SaveResultResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ChangeTaskStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeTaskStatusRequest) Reset()         { *m = ChangeTaskStatusRequest{} }
func (m *ChangeTaskStatusRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeTaskStatusRequest) ProtoMessage()    {}
func (*ChangeTaskStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac1b54aa7dff77fd, []int{4}
}

func (m *ChangeTaskStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeTaskStatusRequest.Unmarshal(m, b)
}
func (m *ChangeTaskStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeTaskStatusRequest.Marshal(b, m, deterministic)
}
func (m *ChangeTaskStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeTaskStatusRequest.Merge(m, src)
}
func (m *ChangeTaskStatusRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeTaskStatusRequest.Size(m)
}
func (m *ChangeTaskStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeTaskStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeTaskStatusRequest proto.InternalMessageInfo

type ChangeTaskStatusResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeTaskStatusResponse) Reset()         { *m = ChangeTaskStatusResponse{} }
func (m *ChangeTaskStatusResponse) String() string { return proto.CompactTextString(m) }
func (*ChangeTaskStatusResponse) ProtoMessage()    {}
func (*ChangeTaskStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac1b54aa7dff77fd, []int{5}
}

func (m *ChangeTaskStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeTaskStatusResponse.Unmarshal(m, b)
}
func (m *ChangeTaskStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeTaskStatusResponse.Marshal(b, m, deterministic)
}
func (m *ChangeTaskStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeTaskStatusResponse.Merge(m, src)
}
func (m *ChangeTaskStatusResponse) XXX_Size() int {
	return xxx_messageInfo_ChangeTaskStatusResponse.Size(m)
}
func (m *ChangeTaskStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeTaskStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeTaskStatusResponse proto.InternalMessageInfo

type UpdateTaskStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTaskStatusRequest) Reset()         { *m = UpdateTaskStatusRequest{} }
func (m *UpdateTaskStatusRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskStatusRequest) ProtoMessage()    {}
func (*UpdateTaskStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac1b54aa7dff77fd, []int{6}
}

func (m *UpdateTaskStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskStatusRequest.Unmarshal(m, b)
}
func (m *UpdateTaskStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskStatusRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTaskStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskStatusRequest.Merge(m, src)
}
func (m *UpdateTaskStatusRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskStatusRequest.Size(m)
}
func (m *UpdateTaskStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskStatusRequest proto.InternalMessageInfo

type UpdateTaskStatusResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTaskStatusResponse) Reset()         { *m = UpdateTaskStatusResponse{} }
func (m *UpdateTaskStatusResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskStatusResponse) ProtoMessage()    {}
func (*UpdateTaskStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac1b54aa7dff77fd, []int{7}
}

func (m *UpdateTaskStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskStatusResponse.Unmarshal(m, b)
}
func (m *UpdateTaskStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskStatusResponse.Marshal(b, m, deterministic)
}
func (m *UpdateTaskStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskStatusResponse.Merge(m, src)
}
func (m *UpdateTaskStatusResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskStatusResponse.Size(m)
}
func (m *UpdateTaskStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskStatusResponse proto.InternalMessageInfo

type HealthCheckRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckRequest) Reset()         { *m = HealthCheckRequest{} }
func (m *HealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*HealthCheckRequest) ProtoMessage()    {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac1b54aa7dff77fd, []int{8}
}

func (m *HealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckRequest.Unmarshal(m, b)
}
func (m *HealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckRequest.Marshal(b, m, deterministic)
}
func (m *HealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckRequest.Merge(m, src)
}
func (m *HealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_HealthCheckRequest.Size(m)
}
func (m *HealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckRequest proto.InternalMessageInfo

type HealthCheckResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac1b54aa7dff77fd, []int{9}
}

func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(m, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("protov3.JobType", JobType_name, JobType_value)
	proto.RegisterEnum("protov3.JobStatus", JobStatus_name, JobStatus_value)
	proto.RegisterType((*AssignTaskToWorkerRequest)(nil), "protov3.AssignTaskToWorkerRequest")
	proto.RegisterType((*AssignTaskToWorkerResponse)(nil), "protov3.AssignTaskToWorkerResponse")
	proto.RegisterType((*SaveResultRequest)(nil), "protov3.SaveResultRequest")
	proto.RegisterType((*SaveResultResponse)(nil), "protov3.SaveResultResponse")
	proto.RegisterType((*ChangeTaskStatusRequest)(nil), "protov3.ChangeTaskStatusRequest")
	proto.RegisterType((*ChangeTaskStatusResponse)(nil), "protov3.ChangeTaskStatusResponse")
	proto.RegisterType((*UpdateTaskStatusRequest)(nil), "protov3.UpdateTaskStatusRequest")
	proto.RegisterType((*UpdateTaskStatusResponse)(nil), "protov3.UpdateTaskStatusResponse")
	proto.RegisterType((*HealthCheckRequest)(nil), "protov3.HealthCheckRequest")
	proto.RegisterType((*HealthCheckResponse)(nil), "protov3.HealthCheckResponse")
}

func init() {
	proto.RegisterFile("protov3/orchestrator.proto", fileDescriptor_ac1b54aa7dff77fd)
}

var fileDescriptor_ac1b54aa7dff77fd = []byte{
	// 537 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xdd, 0x6e, 0xda, 0x4e,
	0x10, 0xc5, 0xff, 0x76, 0xf4, 0x87, 0x30, 0x95, 0x22, 0x67, 0x52, 0x12, 0x70, 0xab, 0x8a, 0xba,
	0xbd, 0x88, 0x52, 0x89, 0xa8, 0xa4, 0x77, 0xbd, 0x32, 0x78, 0xd3, 0x38, 0xe2, 0x4b, 0xb6, 0x11,
	0x6a, 0xa5, 0xca, 0x32, 0xb0, 0xe2, 0x2b, 0x65, 0xa9, 0xd7, 0x20, 0x45, 0x7d, 0x8b, 0x4a, 0x7d,
	0x9a, 0xbe, 0x5c, 0x65, 0xbc, 0x76, 0x0c, 0x86, 0x5c, 0xd9, 0x3b, 0x73, 0xce, 0xd9, 0x19, 0xed,
	0x0f, 0xd4, 0xa5, 0xcf, 0x02, 0xb6, 0xbe, 0xb9, 0x66, 0xfe, 0x70, 0x42, 0x79, 0xe0, 0x7b, 0x01,
	0xf3, 0xab, 0x9b, 0x22, 0xe6, 0x45, 0x4f, 0xfb, 0x2d, 0x41, 0x59, 0xe7, 0x7c, 0x3a, 0x5e, 0x38,
	0x1e, 0x9f, 0x3b, 0xac, 0xcf, 0xfc, 0x39, 0xf5, 0x2d, 0xfa, 0x73, 0x45, 0x79, 0x80, 0x45, 0xc8,
	0xcd, 0xd8, 0xc0, 0x9d, 0x8e, 0x4a, 0x52, 0x45, 0xba, 0x2c, 0x58, 0xff, 0xcf, 0xd8, 0xc0, 0x1c,
	0xe1, 0x07, 0x38, 0x0e, 0xcb, 0xc1, 0xe3, 0x92, 0x96, 0xe4, 0x8a, 0x74, 0x79, 0x52, 0x53, 0xaa,
	0x22, 0xb0, 0x7a, 0xcf, 0x06, 0xce, 0xe3, 0x92, 0x5a, 0xf9, 0x59, 0xf4, 0x83, 0x1f, 0x01, 0x42,
	0x31, 0x0f, 0xbc, 0x60, 0xc5, 0x4b, 0x47, 0x1b, 0x39, 0xa6, 0xe5, 0xf6, 0xa6, 0x63, 0x15, 0x66,
	0xf1, 0xaf, 0xf6, 0x09, 0xd4, 0x7d, 0x33, 0xf1, 0x25, 0x5b, 0x70, 0x8a, 0xe7, 0x90, 0x13, 0x61,
	0xd1, 0x50, 0xe2, 0xa4, 0x7d, 0x86, 0x53, 0xdb, 0x5b, 0x53, 0x8b, 0xf2, 0xd5, 0x43, 0x10, 0x6f,
	0x70, 0x02, 0x72, 0x32, 0xbd, 0x3c, 0x1d, 0xa5, 0xcc, 0xf2, 0x96, 0xb9, 0x0a, 0x98, 0x36, 0x8b,
	0xab, 0x4a, 0x90, 0xff, 0x41, 0x39, 0xf7, 0xc6, 0x54, 0x44, 0xc4, 0x47, 0xad, 0x0c, 0x17, 0x8d,
	0x89, 0xb7, 0x18, 0xd3, 0x70, 0x44, 0xb1, 0x41, 0x74, 0xa5, 0xa6, 0x42, 0x29, 0xdb, 0x8a, 0x02,
	0x43, 0x5b, 0x6f, 0x39, 0xf2, 0x82, 0xfd, 0xb6, 0x6c, 0x4b, 0xd8, 0x5e, 0x02, 0xde, 0x51, 0xef,
	0x21, 0x98, 0x34, 0x26, 0x74, 0x38, 0x8f, 0x1d, 0x45, 0x38, 0xdb, 0xaa, 0x46, 0xe2, 0x2b, 0x1b,
	0xf2, 0xe2, 0x11, 0x50, 0x83, 0x37, 0xf7, 0x9d, 0xba, 0xeb, 0x7c, 0xed, 0x12, 0xd7, 0x26, 0x6d,
	0xc3, 0x6d, 0xe9, 0x66, 0xd3, 0xed, 0xb5, 0xed, 0x2e, 0x69, 0x98, 0xb7, 0x26, 0x31, 0x94, 0xff,
	0xf0, 0x3d, 0x54, 0x12, 0x8d, 0xd5, 0x6b, 0xbb, 0x8d, 0x4e, 0xab, 0xa5, 0xb7, 0x8d, 0x2d, 0x95,
	0x74, 0xf5, 0x0b, 0x0a, 0xc9, 0x53, 0xc5, 0x16, 0xdb, 0xd1, 0x9d, 0x9e, 0x1d, 0x1a, 0xba, 0x4d,
	0xe2, 0x10, 0x63, 0x27, 0xb8, 0x08, 0xa7, 0x29, 0xd5, 0xad, 0x6e, 0x36, 0xc3, 0x24, 0x2c, 0x43,
	0x31, 0x55, 0xb6, 0xc8, 0x17, 0xd3, 0x76, 0x88, 0x45, 0x0c, 0x45, 0xc6, 0x73, 0xc0, 0x54, 0xcb,
	0x76, 0x74, 0xcb, 0x21, 0x86, 0x72, 0x54, 0xfb, 0x2b, 0xc1, 0x59, 0x27, 0x05, 0xb1, 0x4d, 0xfd,
	0xf5, 0x74, 0x48, 0xf1, 0x3b, 0x60, 0x96, 0x13, 0xd4, 0x12, 0xb8, 0x0e, 0x82, 0xad, 0xbe, 0x7b,
	0x56, 0x23, 0x5e, 0x9f, 0x00, 0x3c, 0x31, 0x81, 0x6a, 0x62, 0xc9, 0x50, 0xa6, 0xbe, 0xda, 0xdb,
	0x8b, 0x62, 0x6a, 0x7f, 0x64, 0xb8, 0xa8, 0x7b, 0xc3, 0xf9, 0xd8, 0x67, 0xab, 0xc5, 0x28, 0xba,
	0x23, 0xde, 0xa0, 0x0f, 0xca, 0x2e, 0x2b, 0x58, 0x49, 0xc2, 0x0e, 0x10, 0xa6, 0xbe, 0x7d, 0x46,
	0x21, 0x66, 0xef, 0x83, 0xb2, 0x4b, 0x53, 0x2a, 0xf8, 0x00, 0x83, 0xa9, 0xe0, 0x43, 0x28, 0xe2,
	0x1d, 0xbc, 0x48, 0x41, 0x87, 0x4f, 0x9b, 0x67, 0x01, 0x55, 0x5f, 0xef, 0x6f, 0x46, 0x49, 0x75,
	0xf8, 0x76, 0x5c, 0xbd, 0xde, 0x08, 0xf8, 0x20, 0xb7, 0xf9, 0xde, 0xfc, 0x0b, 0x00, 0x00, 0xff,
	0xff, 0x7a, 0xa1, 0x5a, 0xeb, 0xb4, 0x04, 0x00, 0x00,
}
