name: Task-Zephyr-Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
          
      - name: Build Orchestrator
        working-directory: ./orchestrator
        run: go build -v ./...
        
      - name: Build Worker
        working-directory: ./worker
        run: go build -v ./...