name: Test Worker
on: ["push"]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.x"

      - name: Verify Worker Dependencies
        working-directory: ./worker
        run: go mod verify
        
      - name: Verify Orchestrator Dependencies
        working-directory: ./orchestrator
        run: go mod verify
        
      - name: Test Workers
        working-directory: ./worker
        run: go test ./...
    